// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfgpkwbjigghtxnrmdha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmZ3Brd2JqaWdnaHR4bnJtZGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTA1NzMsImV4cCI6MjA3MTAyNjU3M30.aLahGQCW5v9UqE58WGXqKZhj-a7Otaaou7gLmpBUha8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});